### ISSUE TITLE
Not Connected.

### ISSUE THREAD

**Issue by youquzhiji** [tomvita/PointerSearcher-SE#4]
So I tried to connect to my switch with a game running, somehow it always says "not connected". The exception your program handles is the following.
```
System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=No connection could be made because the target machine actively refused it 192.168.2.44:7331
  Source=System
  StackTrace:
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at PointerSearcher.Form1.<>c__DisplayClass47_0.<button2_Click>b__0() in C:\Users\luigi\Downloads\PointerSearcher-SE-master\PointerSearcher\Form1.cs:line 827
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

I'm not sure if there is anything to do with atomsphere's host setting or other problem.

**Comment by FloDoc** [comment]
I am also having "no connection" problems. Seems like all other tools connect but pointer searcher
